### ISSUE TITLE
Exception: Population Set Attribute Error: Number of values and population size do not match!

### ISSUE THREAD

**Issue by achillesrasquinha** [anyoptimization/pymoo#242]
I've been trying to program an optimization problem using `pymoo`.
The following is the problem.

<img width="485" alt="Screen Shot 2022-01-23 at 10 45 36 PM" src="https://user-images.githubusercontent.com/9742568/150723448-3da01be2-89b5-474e-9af4-e66706791c6c.png">

`v` represents a vector of values to be determined. S is a known matrix of coefficients.

My problem's `_evaluate` function is as follows:

```python
def _evaluate(self, x, out, *args, **kwargs):
    model    = self.model
    X        = np.transpose(x)

    coeff    = _get_obj_coeff_arr(model)
    S        = model.sparse_stoichiometric_matrix

    out["F"] = np.dot(np.transpose(coeff), X)
    out["G"] = np.dot(S, X)
```

**Note:** coeff is of size `(190, 1)` and the size of S is `(72, 190)`. The shape of X provided initially was `(190, 100)`.

However, I am not sure why I get the following error.

```
Traceback (most recent call last):
  File "/Users/achilles/.venv/lib/python3.9/site-packages/bpyutils/commands/__init__.py", line 40, in command
    return _command(**ARGUMENTS)
  File "/Users/achilles/.venv/lib/python3.9/site-packages/bpyutils/commands/__init__.py", line 120, in _command
    callable(**args)
  File "/Users/achilles/dev/fluxml/src/fluxml/data/__init__.py", line 43, in get_data
    print(model.optimize())
  File "/Users/achilles/dev/fluxml/src/fluxml/cobra/model.py", line 35, in optimize
    solution  = problem.solve(algorithm = algorithm)
  File "/Users/achilles/dev/fluxml/src/fluxml/cobra/optimization.py", line 95, in solve
    result  = minimize(problem, algorithm_instance)
  File "/Users/achilles/.venv/lib/python3.9/site-packages/pymoo/optimize.py", line 83, in minimize
    res = algorithm.run()
  File "/Users/achilles/.venv/lib/python3.9/site-packages/pymoo/core/algorithm.py", line 213, in run
    self.next()
  File "/Users/achilles/.venv/lib/python3.9/site-packages/pymoo/core/algorithm.py", line 233, in next
    self.evaluator.eval(self.problem, infills, algorithm=self)
  File "/Users/achilles/.venv/lib/python3.9/site-packages/pymoo/core/evaluator.py", line 95, in eval
    self._eval(problem, pop[I], evaluate_values_of=evaluate_values_of, **kwargs)
  File "/Users/achilles/.venv/lib/python3.9/site-packages/pymoo/core/evaluator.py", line 121, in _eval
    pop.set(key, val)
  File "/Users/achilles/.venv/lib/python3.9/site-packages/pymoo/core/population.py", line 58, in set
    raise Exception("Population Set Attribute Error: Number of values and population size do not match!")
Exception: Population Set Attribute Error: Number of values and population size do not match!
```

**Comment by julesy89** [comment]
Sorry for the late reply. Have you checked the dimensionality of `out["F"]`?
Also, equality constraints will need to be handled differently if you intend to use a GA.

Please let me know if still an open issue you are facing anyway.
