### ISSUE TITLE
AttributeError: 'Population' object has no attribute 'CV'

### ISSUE THREAD

**Issue by siddas27** [anyoptimization/pymoo#263]
I was trying the code in the [link](https://pymoo.org/getting_started/part_2.html) with modification of the problem as:
```
class MyProblem(ElementwiseProblem):

    def __init__(self):
        super().__init__(n_var=1,
                         n_obj=2,
                         n_constr=2,
                         xl=np.array([0.0]),
                         xu=np.array([1.0]))

    def _evaluate(self, t, out, *args, **kwargs):
        f1 = - t * math.sin(10 * math.pi * t)
        f2 = - 2.5 * t * math.cos(3 * math.pi * t)

        g1 = -t
        g2 = t

        out["F"] = [f1, f2]
        out["G"] = [g1, g2]
```
And am getting the following error:

```
Traceback (most recent call last):
  File "/Users/PycharmProjects/CSE598BIAIO/MiniProject3/using_pymoo.py", line 45, in <module>
    res = minimize(problem,
  File "/Users/miniforge3/envs/Cox/lib/python3.8/site-packages/pymoo/optimize.py", line 83, in minimize
    res = algorithm.run()
  File "/Users/miniforge3/envs/Cox/lib/python3.8/site-packages/pymoo/core/algorithm.py", line 213, in run
    self.next()
  File "/Users/miniforge3/envs/Cox/lib/python3.8/site-packages/pymoo/core/algorithm.py", line 229, in next
    infills = self.infill()
  File "/Users/miniforge3/envs/Cox/lib/python3.8/site-packages/pymoo/core/algorithm.py", line 269, in infill
    infills = self._infill()
  File "/Users/miniforge3/envs/Cox/lib/python3.8/site-packages/pymoo/algorithms/base/genetic.py", line 86, in _infill
    off = self.mating.do(self.problem, self.pop, self.n_offsprings, algorithm=self)
  File "/Users/miniforge3/envs/Cox/lib/python3.8/site-packages/pymoo/core/infill.py", line 34, in do
    _off = self._do(problem, pop, n_remaining, **kwargs)
  File "/Users/miniforge3/envs/Cox/lib/python3.8/site-packages/pymoo/core/mating.py", line 28, in _do
    parents = self.selection.do(pop, n_select, self.crossover.n_parents, **kwargs)
  File "/Users/miniforge3/envs/Cox/lib/python3.8/site-packages/pymoo/core/selection.py", line 36, in do
    return self._do(pop, n_select, n_parents, **kwargs)
  File "/Users/miniforge3/envs/Cox/lib/python3.8/site-packages/pymoo/operators/selection/tournament.py", line 47, in _do
    S = self.f_comp(pop, P, **kwargs)
  File "/Users/miniforge3/envs/Cox/lib/python3.8/site-packages/pymoo/algorithms/moo/nsga2.py", line 35, in binary_tournament
    a_cv, a_f, b_cv, b_f, = pop[a].CV[0], pop[a].F, pop[b].CV[0], pop[b].F
AttributeError: 'Population' object has no attribute 'CV'
```

**Comment by julesy89** [comment]
`t` is a vector and not a scalar! The input `x` in my code snippet below is the numpy array. If you plan to do scalar operators you have to do this on the floats of the array. 

Please see my code below.

```
class MyProblem(ElementwiseProblem):

    def __init__(self):
        super().__init__(n_var=1,
                         n_obj=2,
                         n_constr=2,
                         xl=np.array([0.0]),
                         xu=np.array([1.0]))

    def _evaluate(self, x, out, *args, **kwargs):
        t = x[0]
        f1 = - t * math.sin(10 * math.pi * t)
        f2 = - 2.5 * t * math.cos(3 * math.pi * t)

        g1 = -t
        g2 = t

        out["F"] = [f1, f2]
        out["G"] = [g1, g2]
```
