### ISSUE TITLE
Adaptive PSO leads to TypeError in func_norm_euclidean_distance

### ISSUE THREAD

**Issue by marisn** [anyoptimization/pymoo#355]
While running ElementwiseProblem with StarmapParallelization and PSO algorithm with particular settings I always encounter a TypeError at the end of second generation run in func_norm_euclidean_distance. I managed to work around by saving to file each X value at evaluation and then initializing population from text file with X values. After such restart optimization was able to run for 100 generations without any problems.
I didn't observe the problem with modified input data; number of parallel processes does not matter; I didn't try to run as a single process or under valgrind as it would require at least two days of runtime.

I modified pso._advance code to dump self to file at the start of _advance function. Here's the dump:
http://www.gisnet.lv/~marisn/pso_adaptive_crash.dill

Test code leading to the same traceback:
```
import dill
f = open("pso_adaptive_crash.dill", "rb")
o = dill.load(f)
o._adapt()
```

Original traceback (stripped paths to venv for shortness):
```
AttributeError: 'float' object has no attribute 'sqrt'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "optimize_svm.py", line 231, in <module>
    res = minimize(problem_svm,
  File "lib/python3.10/site-packages/pymoo/optimize.py", line 67, in minimize
    res = algorithm.run()
  File "lib/python3.10/site-packages/pymoo/core/algorithm.py", line 141, in run
    self.next()
  File "lib/python3.10/site-packages/pymoo/core/algorithm.py", line 162, in next
    self.advance(infills=infills)
  File "lib/python3.10/site-packages/pymoo/core/algorithm.py", line 228, in advance
    val = self._advance(infills=infills, **kwargs)
  File "lib/python3.10/site-packages/pymoo/algorithms/soo/nonconvex/pso.py", line 281, in _advance
    self._adapt()
  File "lib/python3.10/site-packages/pymoo/algorithms/soo/nonconvex/pso.py", line 294, in _adapt
    D = norm_eucl_dist(self.problem, X, X)
  File "lib/python3.10/site-packages/pymoo/util/misc.py", line 107, in norm_eucl_dist
    return norm_eucl_dist_by_bounds(A, B, *problem.bounds(), **kwargs)
  File "lib/python3.10/site-packages/pymoo/util/misc.py", line 103, in norm_eucl_dist_by_bounds
    return vectorized_cdist(A, B, func_dist=func_norm_euclidean_distance(xl, xu), **kwargs)
  File "lib/python3.10/site-packages/pymoo/util/misc.py", line 170, in vectorized_cdist
    D = func_dist(u, v, **kwargs)
  File "lib/python3.10/site-packages/pymoo/util/misc.py", line 99, in <lambda>
    return lambda a, b: np.sqrt((((a - b) / (xu - xl)) ** 2).sum(axis=1))
TypeError: loop of ufunc does not support argument 0 of type float which has no callable sqrt method
```
Python 3.10.9, numpy 1.23.5, pymoo 0.6.0

**Comment by marisn** [comment]
As soon as I opened the bug report, it hit me. The error was in initial X – by error I produced an array of object and not an array of np.float. As the data itself in X was floats, evaluation was just fine as long as X it self wasn't required to be an array of floats and for norm_eucl_dist it has to be. Thus evaluation of first generation could run just fine as values inside were fine. Stupid noob mistake :-(
