### ISSUE TITLE
Problem running in Dask

### ISSUE THREAD

**Issue by davide-q** [anyoptimization/pymoo#363]
Trying to run in Dask a very simple ElementwiseProblem with NSGA2 fails with

```
==========================================================
n_gen  |  n_eval  | n_nds  |      eps      |   indicator
==========================================================
     1 |       40 |      2 |             - |             -
2023-01-06 15:17:18,915 - distributed.protocol.pickle - INFO - Failed to serialize <pymoo.core.problem.ElementwiseEvaluationFunction object at 0x14b674ba97e0>. Exception: 'client'
Traceback (most recent call last):
  File "~/venvs/pymoo/lib/python3.10/site-packages/distributed/worker.py", line 2935, in dumps_function
    result = cache_dumps[func]
  File "~/venvs/pymoo/lib/python3.10/site-packages/distributed/collections.py", line 24, in __getitem__
    value = super().__getitem__(key)
  File "/home/sw/spack-v0.18.0-a/var/spack/environments/p3-10-4_g12-1-0/.spack-env/._view/673b6vfeghr75owgk3b4zqzu65kytvwp/lib/python3.10/collections/__init__.py", line 1106, in __getitem__
    raise KeyError(key)
KeyError: <pymoo.core.problem.ElementwiseEvaluationFunction object at 0x14b674ba97e0>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "~/venvs/pymoo/lib/python3.10/site-packages/distributed/protocol/pickle.py", line 46, in dumps
    result = pickle.dumps(x, **dump_kwargs)
  File "~/venvs/pymoo/lib/python3.10/site-packages/pymoo/core/problem.py", line 57, in __getstate__
    state.pop("client")
KeyError: 'client'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "~/repositories/dask/dask_pymoo/pymoo_dask.py", line 70, in <module>
    res = minimize(problem,
  File "~/venvs/pymoo/lib/python3.10/site-packages/pymoo/optimize.py", line 67, in minimize
    res = algorithm.run()
  File "~/venvs/pymoo/lib/python3.10/site-packages/pymoo/core/algorithm.py", line 141, in run
    self.next()
  File "~/venvs/pymoo/lib/python3.10/site-packages/pymoo/core/algorithm.py", line 161, in next
    self.evaluator.eval(self.problem, infills, algorithm=self)
  File "~/venvs/pymoo/lib/python3.10/site-packages/pymoo/core/evaluator.py", line 69, in eval
    self._eval(problem, pop[I], evaluate_values_of, **kwargs)
  File "~/venvs/pymoo/lib/python3.10/site-packages/pymoo/core/evaluator.py", line 90, in _eval
    out = problem.evaluate(X, return_values_of=evaluate_values_of, return_as_dictionary=True, **kwargs)
  File "~/venvs/pymoo/lib/python3.10/site-packages/pymoo/core/problem.py", line 187, in evaluate
    _out = self.do(X, return_values_of, *args, **kwargs)
  File "~/venvs/pymoo/lib/python3.10/site-packages/pymoo/core/problem.py", line 227, in do
    self._evaluate_elementwise(X, out, *args, **kwargs)
  File "~/venvs/pymoo/lib/python3.10/site-packages/pymoo/core/problem.py", line 245, in _evaluate_elementwise
    elems = self.elementwise_runner(f, X)
  File "~/venvs/pymoo/lib/python3.10/site-packages/pymoo/core/problem.py", line 52, in __call__
    jobs = [self.client.submit(f, x) for x in X]
  File "~/venvs/pymoo/lib/python3.10/site-packages/pymoo/core/problem.py", line 52, in <listcomp>
    jobs = [self.client.submit(f, x) for x in X]
  File "~/venvs/pymoo/lib/python3.10/site-packages/distributed/client.py", line 1886, in submit
    futures = self._graph_to_futures(
  File "~/venvs/pymoo/lib/python3.10/site-packages/distributed/client.py", line 3013, in _graph_to_futures
    dsk = dsk.__dask_distributed_pack__(self, keyset, annotations)
  File "~/venvs/pymoo/lib/python3.10/site-packages/dask/highlevelgraph.py", line 1078, in __dask_distributed_pack__
    "state": layer.__dask_distributed_pack__(
  File "~/venvs/pymoo/lib/python3.10/site-packages/dask/highlevelgraph.py", line 432, in __dask_distributed_pack__
    dsk = toolz.valmap(dumps_task, dsk)
  File "~/venvs/pymoo/lib/python3.10/site-packages/toolz/dicttoolz.py", line 85, in valmap
    rv.update(zip(d.keys(), map(func, d.values())))
  File "~/venvs/pymoo/lib/python3.10/site-packages/distributed/worker.py", line 2973, in dumps_task
    return {"function": dumps_function(task[0]), "args": warn_dumps(task[1:])}
  File "~/venvs/pymoo/lib/python3.10/site-packages/distributed/worker.py", line 2937, in dumps_function
    result = pickle.dumps(func)
  File "~/venvs/pymoo/lib/python3.10/site-packages/distributed/protocol/pickle.py", line 58, in dumps
    result = cloudpickle.dumps(x, **dump_kwargs)
  File "~/venvs/pymoo/lib/python3.10/site-packages/cloudpickle/cloudpickle_fast.py", line 73, in dumps
    cp.dump(obj)
  File "~/venvs/pymoo/lib/python3.10/site-packages/cloudpickle/cloudpickle_fast.py", line 632, in dump
    return Pickler.dump(self, obj)
  File "~/venvs/pymoo/lib/python3.10/site-packages/pymoo/core/problem.py", line 57, in __getstate__
    state.pop("client")
KeyError: 'client'
```

Switching to regular (non elementwise) Problem succeeds only if the population size is selected equal to 10, which I suspect has something to do with `_evaluate`. Otherwise it fails with the dreadful `Problem Error: F can not be set, expected shape (40, 2) but provided (10, 2)', ValueError('cannot reshape array of size 20 into shape (40,2)'`

Am I doing something wrong or is this a bug?

**Comment by blankjul** [comment]
Can you provide your source code to reproduce your error?

The error message shows that 40 individuals have been provided, but only 10 are returned by the evaluation function.
Any reason why this could be the case in your implementation?

**Comment by davide-q** [comment]
@blankjul thanks for your message. The error you mention is for the non-elementwise case which I am not sure is suitable for dask parallelization since it already does numpy parallelization. The most annoying error is the `KeyError` one for which I have found a workaround which I am testing right now. The workaround is putting a `try: except KeyError` around line 57 of `pymoo/core/problem.py` which seems to having been placed there exactly to solve the issue it is creating.

**Comment by davide-q** [comment]
Anyway my code is the following

```python
import numpy as np
from pymoo.core.problem import ElementwiseProblem

tot_var = 10
class MyProblem(ElementwiseProblem):

    def __init__(self, **kwargs):
        super().__init__(n_var=tot_var,
                         n_obj=2,
                         n_ieq_constr=0,
                         xl=np.array([0]*tot_var),
                         xu=np.array([1]*tot_var),
                         elementwise=True,
                         **kwargs,
                        )

    def _evaluate(self, x, out, *args, **kwargs):
        f1 = 0
        f2 = 0
        prev = 0
        prev_prev = 0
        for xi in x:
            f1 += -xi * xi
            f2 += -(xi - prev) * (xi - prev)
            prev_prev = prev
            prev = xi

        out["F"] = [f1, f2]

from pymoo.algorithms.moo.nsga2 import NSGA2
from pymoo.operators.crossover.sbx import SBX
from pymoo.operators.mutation.pm import PM
from pymoo.operators.sampling.rnd import FloatRandomSampling

algorithm = NSGA2(
    pop_size=40,
    n_offsprings=10,
    sampling=FloatRandomSampling(),
    crossover=SBX(prob=0.9, eta=15),
    mutation=PM(eta=20),
    eliminate_duplicates=True
)

from pymoo.termination import get_termination
termination = get_termination("n_gen", 2000)

from dask_mpi import initialize
initialize()
from distributed import Client
client = Client()
from pymoo.core.problem import DaskParallelization
runner = DaskParallelization(client)
problem = MyProblem(elementwise_runner=runner)

from pymoo.optimize import minimize
res = minimize(problem,
               algorithm,
               termination,
               seed=15,
               save_history=True,
               verbose=True,
              )
client.close()

X = res.X
F = res.F

import matplotlib
matplotlib.rcParams['figure.max_open_warning']=50

import matplotlib.pyplot as plt
plt.rcParams['figure.figsize'] = [20, 10]

fig = plt.figure()
ax = fig.add_subplot()

ax.scatter(F[:, 0], F[:, 1], s=30, facecolors='none', edgecolors='blue')
plt.title("Objective Space")
plt.savefig("1_objective_space.png")

for i,x in enumerate(X):
    plt.figure(figsize=(7, 5))
    plt.plot(x, color='r')
    #plt.xlim(xl[0], xu[0])
    plt.ylim(0, 1)
    plt.title("Solution with " + str(F[i]))
    plt.savefig(str(i+2) + "_solution.png")
```

**Comment by davide-q** [comment]
> @blankjul thanks for your message. The error you mention is for the non-elementwise case which I am not sure is suitable for dask parallelization since it already does numpy parallelization. The most annoying error is the `KeyError` one for which I have found a workaround which I am testing right now. The workaround is putting a `try: except KeyError` around line 57 of `pymoo/core/problem.py` which seems to having been placed there exactly to solve the issue it is creating.

That workaround fixes the problem. Do you want me to make a PR about it?

**Comment by blankjul** [comment]
I am not sure if I can follow what line it actually is. Can you do a PR just for clarity? 

Is it 

```
            try:
                out[k] = v.astype(np.float64)
            except:
                pass
```

?

**Comment by cyrilpic** [comment]
I think it could be a similar issue to #313. 

This line should probably have a `, None` in the pop call (similarly to 1a46d1ae3c852912e09ac9b9cc20c4322ad237e8 for Starmap)
https://github.com/anyoptimization/pymoo/blob/41c7fa9bd271b1db0ec74b0b62621902000e97cb/pymoo/core/problem.py#L57

**Comment by davide-q** [comment]
> I think it could be a similar issue to #313.
> 
> This line should probably have a `, None` in the pop call (similarly to [1a46d1a](https://github.com/anyoptimization/pymoo/commit/1a46d1ae3c852912e09ac9b9cc20c4322ad237e8) for Starmap)
> 
> https://github.com/anyoptimization/pymoo/blob/41c7fa9bd271b1db0ec74b0b62621902000e97cb/pymoo/core/problem.py#L57

Yes, that's it.

I wrote it as 

```python
        try:
            state.pop("client")
        except KeyError:
            pass
```

but the `None` is more elegant solution.

@blankjul : perhaps you are looking at a different file or a different branch? I can do the PR later today if it's still unclear

**Comment by blankjul** [comment]
Got it! Should be fixed now.

(Please let me know if not)
