### ISSUE TITLE
Parallelization: only one process is working when I use multiprocessing in pymoo

### ISSUE THREAD

**Issue by cjx2020** [anyoptimization/pymoo#374]
When I use the multiprocessing to accelerate my code, I find that only one process is working, and there is no significant acceleration

I use the similar setting as below.

import multiprocessing
from pymoo.algorithms.soo.nonconvex.ga import GA
from pymoo.optimize import minimize

# initialize the thread pool and create the runner
n_proccess = 8
pool = multiprocessing.Pool(n_proccess)
runner = StarmapParallelization(pool.starmap)

# define the problem by passing the starmap interface of the thread pool
problem = MyProblem(elementwise_runner=runner)

res = minimize(problem, GA(), termination=("n_gen", 200), seed=1)
print('Threads:', res.exec_time)

pool.close()

**Comment by cjx2020** [comment]
![image](https://user-images.githubusercontent.com/63455193/215784132-49dc7ac6-725a-4d80-bb26-f6daaa7cf268.png)

**Comment by cyrilpic** [comment]
Which version of pymoo are you using?

Only the problem evaluation step is parallelize, so if `MyProblem` is fast enough ( < ~1ms per function call), you could end up with the processor usage you are showing.

**Comment by cjx2020** [comment]
my pymoo version is 0.6.0, and because of my knowledge of multiprocessing is so limited, and I can't find the related setting from the pymoo source code. myproblem is so complexed with about 1,000 variables

**Comment by cyrilpic** [comment]
For pymoo 0.6.0, you need to make sure `MyProblem` is a subclass of `ElementwiseProblem`.

**Comment by cjx2020** [comment]
yes, my problem class is inherited by ElementwiseProblem. I have tried the multithread according the pymoo guide, and it works well. But the multiprocessing doesn't work well

**Comment by cjx2020** [comment]
I used checkpoint in my code, and I find that the checkpoint can't support the multiprocessing from the former closed issue. But before I load the checkpoint, the multiprocessing has only worked in one process.

**Comment by cyrilpic** [comment]
[`viztracer`](https://github.com/gaogaotiantian/viztracer) can be used to debug multiprocessing

**Comment by cjx2020** [comment]
ok, thanks. I guess there may be some errors in my problem defination, the real multiprocessing is only created, but doesn't submit to my problem

**Comment by cjx2020** [comment]
@cyrilpic When I run multiprocessing, I meet the below error, do you know how to solve it ?

Traceback (most recent call last):
  File "D:\program\battle2022_modify_ver\my_core\20230131\optimal_run_02.py", line 340, in <module>
    main(check_location)
  File "D:\program\battle2022_modify_ver\my_core\20230131\optimal_run_02.py", line 236, in main
    res = minimize(problem=my_problem,
  File "C:\Users\jxc\anaconda3\envs\py3.8\lib\site-packages\pymoo\optimize.py", line 67, in minimize
    res = algorithm.run()
  File "C:\Users\jxc\anaconda3\envs\py3.8\lib\site-packages\pymoo\core\algorithm.py", line 141, in run
    self.next()
  File "C:\Users\jxc\anaconda3\envs\py3.8\lib\site-packages\pymoo\core\algorithm.py", line 161, in next
    self.evaluator.eval(self.problem, infills, algorithm=self)
  File "C:\Users\jxc\anaconda3\envs\py3.8\lib\site-packages\pymoo\core\evaluator.py", line 69, in eval
    self._eval(problem, pop[I], evaluate_values_of, **kwargs)
  File "C:\Users\jxc\anaconda3\envs\py3.8\lib\site-packages\pymoo\core\evaluator.py", line 90, in _eval
    out = problem.evaluate(X, return_values_of=evaluate_values_of, return_as_dictionary=True, **kwargs)
  File "C:\Users\jxc\anaconda3\envs\py3.8\lib\site-packages\pymoo\core\problem.py", line 187, in evaluate
    _out = self.do(X, return_values_of, *args, **kwargs)
  File "C:\Users\jxc\anaconda3\envs\py3.8\lib\site-packages\pymoo\core\problem.py", line 227, in do
    self._evaluate_elementwise(X, out, *args, **kwargs)
  File "C:\Users\jxc\anaconda3\envs\py3.8\lib\site-packages\pymoo\core\problem.py", line 245, in _evaluate_elementwise
    elems = self.elementwise_runner(f, X)
  File "C:\Users\jxc\anaconda3\envs\py3.8\lib\site-packages\pymoo\core\problem.py", line 37, in __call__
    return list(self.starmap(f, [[x] for x in X]))
  File "C:\Users\jxc\anaconda3\envs\py3.8\lib\multiprocessing\pool.py", line 372, in starmap
    return self._map_async(func, iterable, starmapstar, chunksize).get()
  File "C:\Users\jxc\anaconda3\envs\py3.8\lib\multiprocessing\pool.py", line 771, in get
    raise self._value
  File "C:\Users\jxc\anaconda3\envs\py3.8\lib\multiprocessing\pool.py", line 537, in _handle_tasks
    put(task)
  File "C:\Users\jxc\anaconda3\envs\py3.8\lib\multiprocessing\connection.py", line 206, in send
    self._send_bytes(_ForkingPickler.dumps(obj))
  File "C:\Users\jxc\anaconda3\envs\py3.8\lib\multiprocessing\reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
  File "C:\Users\jxc\anaconda3\envs\py3.8\lib\site-packages\pymoo\core\problem.py", line 41, in __getstate__
    state.pop("starmap")
KeyError: 'starmap'

Process finished with exit code 1

**Comment by cyrilpic** [comment]
This is issue #313. If you update to pymoo 0.6.0.1 that should be fixed.

**Comment by cjx2020** [comment]
It works well, after I update pymoo to 0.6.0.1. Thanks sincerely.

**Comment by blankjul** [comment]
@cyrilpic Thanks for taking care of this issue!
