### ISSUE TITLE
Ask-and-tell (problem-independent) exception with NelderMead

### ISSUE THREAD

**Issue by npielawski** [anyoptimization/pymoo#404]
I get an issue running the Ask-and-tell (problem-independent) sampling using the NelderMead optimizer.

```python
problem = Problem(n_var=3, n_obj=1, n_constr=0, xl=np.zeros(30), xu=np.ones(30))
algorithm = NelderMead()
algorithm.setup(problem, termination=NoTermination());

# First iteration
pop = algorithm.ask()
X = pop.get("X")
print(X.shape) # (20, 3)

static = StaticProblem(problem, F=np.random.randn(20))
Evaluator().eval(static, pop)
algorithm.tell(infills=pop)

# Second iteration
pop = algorithm.ask()
X = pop.get("X")
print(X.shape) # (4, 3)
static = StaticProblem(problem, F=np.random.randn(4))
Evaluator().eval(static, pop)
```
The last operation causes this exception to be caught:
```bash
Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/site-packages/pymoo/core/problem.py", line 285, in _format_dict
    v = v.reshape(shape[name])
ValueError: cannot reshape array of size 4 into shape (3,1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/lib/python3.10/site-packages/pymoo/core/evaluator.py", line 69, in eval
    self._eval(problem, pop[I], evaluate_values_of, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/pymoo/core/evaluator.py", line 90, in _eval
    out = problem.evaluate(X, return_values_of=evaluate_values_of, return_as_dictionary=True, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/pymoo/core/problem.py", line 187, in evaluate
    _out = self.do(X, return_values_of, *args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/pymoo/core/problem.py", line 232, in do
    out = self._format_dict(out, len(X), return_values_of)
  File "/opt/conda/lib/python3.10/site-packages/pymoo/core/problem.py", line 287, in _format_dict
    raise Exception(
Exception: ('Problem Error: F can not be set, expected shape (3, 1) but provided (4,)', ValueError('cannot reshape array of size 4 into shape (3,1)'))
```

Somehow the evaluator expects three entries (and it does work if I feed ```F=np.random.randn(3)```). Is this correct behavior, or is it a bug?

Thanks in advance for your help!

I am using pymoo version 0.6.0.1.

**Comment by blankjul** [comment]
Took me a while to find too. The problem is that the evaluator skips solutions that are already evaluated. 
Here, NelderAndMead returns a solution that already has `F` being set. This happens only once, in the beginning, to avoid special treatment depending on if a starting solution is provided and/or it is already evaluated.

```
from pymoo.algorithms.soo.nonconvex.nelder import NelderMead
from pymoo.core.evaluator import Evaluator
from pymoo.core.problem import Problem
from pymoo.core.termination import NoTermination
from pymoo.problems.static import StaticProblem


import numpy as np

problem = Problem(n_var=3, n_obj=1, n_constr=0, xl=np.zeros(3), xu=np.ones(3))
algorithm = NelderMead()
algorithm.setup(problem, termination=NoTermination())

# First iteration
pop = algorithm.ask()
X = pop.get("X")
print(X.shape) # (20, 3)

static = StaticProblem(problem, F=np.random.randn(len(X)))
Evaluator(skip_already_evaluated=False).eval(static, pop)
algorithm.tell(infills=pop)

# Second iteration
pop = algorithm.ask()
X = pop.get("X")
print(X.shape) # (4, 3)
static = StaticProblem(problem, F=np.random.randn(len(X)))
Evaluator(skip_already_evaluated=False).eval(static, pop)

algorithm.tell(infills=pop)

``
will fix it.



In the more recent pymoo version (the one you are using), you can even simplify it to:

```
import numpy as np

from pymoo.algorithms.soo.nonconvex.nelder import NelderMead
from pymoo.core.problem import Problem
from pymoo.core.termination import NoTermination

problem = Problem(n_var=3, n_obj=1, n_constr=0, xl=np.zeros(3), xu=np.ones(3))
algorithm = NelderMead()
algorithm.setup(problem, termination=NoTermination())

# First iteration
pop = algorithm.ask()
pop.set("F", np.random.uniform(size=(len(pop), 1)))
algorithm.tell(infills=pop)

# Second iteration
pop = algorithm.ask()
pop.set("F", np.random.uniform(size=(len(pop), 1)))
algorithm.tell(infills=pop)
```

Can you give me the link to the documentation where your code is coming from? I will update it then.

**Comment by npielawski** [comment]
Great, thanks so much for your help! Something else happens on the next step (also occurs with CMA-ES). Starting from your code above:

```python
In [11]: pop = algorithm.ask(); pop.get("X").shape
Out[11]: (3,)

In [12]: pop.set("F", np.random.uniform(size=(len(pop), 1)))
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[12], line 1
----> 1 pop.set("F", np.random.uniform(size=(len(pop), 1)))

TypeError: object of type 'Individual' has no len()

In [13]: pop.set("F", np.random.uniform(size=(3, 1)))
Out[13]: <pymoo.core.individual.Individual at 0x400c1e43d0>

In [14]: algorithm.tell(infills=pop)
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[14], line 1
----> 1 algorithm.tell(infills=pop)

File /opt/conda/lib/python3.10/site-packages/pymoo/core/algorithm.py:298, in Algorithm.tell(self, *args, **kwargs)
    297 def tell(self, *args, **kwargs):
--> 298     return self.advance(*args, **kwargs)

File /opt/conda/lib/python3.10/site-packages/pymoo/core/algorithm.py:228, in Algorithm.advance(self, infills, **kwargs)
    223     self._post_advance()
    225 else:
    226 
    227     # call the implementation of the advance method - if the infill is not None
--> 228     val = self._advance(infills=infills, **kwargs)
    230     # always advance to the next iteration - except if the algorithm returns False
    231     if val is None or val:

File /opt/conda/lib/python3.10/site-packages/pymoo/core/algorithm.py:382, in LoopwiseAlgorithm._advance(self, infills, **kwargs)
    380     self.generator = self._next()
    381 try:
--> 382     self.state = self.generator.send(infills)
    383 except StopIteration:
    384     self.generator = None

File /opt/conda/lib/python3.10/site-packages/pymoo/algorithms/soo/nonconvex/nelder.py:154, in NelderMead._next(self)
    152     self.is_simplex_initialized = True
    153 else:
--> 154     yield from self._step()

File /opt/conda/lib/python3.10/site-packages/pymoo/algorithms/soo/nonconvex/nelder.py:248, in NelderMead._step(self)
    245     x_shrink = x_best + self.delta * (x_others - x_best)
    246     pop[1:] = yield Population.new(X=x_shrink)
--> 248 self.pop = FitnessSurvival().do(self.problem, pop, n_survive=len(pop))

File /opt/conda/lib/python3.10/site-packages/pymoo/core/survival.py:55, in Survival.do(self, problem, pop, n_survive, return_indices, *args, **kwargs)
     52         survivors = Population.merge(survivors, pop[infeas[:n_remaining]])
     54 else:
---> 55     survivors = self._do(problem, pop, *args, n_survive=n_survive, **kwargs)
     57 if return_indices:
     58     H = {}

File /opt/conda/lib/python3.10/site-packages/pymoo/algorithms/soo/nonconvex/ga.py:27, in FitnessSurvival._do(self, problem, pop, n_survive, **kwargs)
     26 def _do(self, problem, pop, n_survive=None, **kwargs):
---> 27     F, cv = pop.get("F", "cv")
     28     assert F.shape[1] == 1, "FitnessSurvival can only used for single objective single!"
     29     S = np.lexsort([F[:, 0], cv])

File /opt/conda/lib/python3.10/site-packages/pymoo/core/population.py:67, in Population.get(self, to_numpy, *args, **kwargs)
     65 # to numpy array if desired - default true
     66 if to_numpy:
---> 67     res = [np.array(e) for e in res]
     69 # return as tuple or single value
     70 if len(args) == 1:

File /opt/conda/lib/python3.10/site-packages/pymoo/core/population.py:67, in <listcomp>(.0)
     65 # to numpy array if desired - default true
     66 if to_numpy:
---> 67     res = [np.array(e) for e in res]
     69 # return as tuple or single value
     70 if len(args) == 1:
```

Another thing, I think this line is hardcoding the scale of the initialization of the simplex: https://github.com/anyoptimization/pymoo/blob/ff2e308d9e507ebc2b37e3b9d3fa1db7d81ce4ef/pymoo/algorithms/soo/nonconvex/nelder.py#L146
Which should be:
```python
simplex = pop_from_array_or_individual(initialize_simplex(self.problem, self.x0.X, scale=self.init_simplex_scale))
```

**Comment by blankjul** [comment]
Oh yeah. I should have mentioned that not all algorithms support the Ask and Tell interface throughout the whole run. NelderMead and CMAES both don't (they would need a major re-implementation to make it work).

**Comment by npielawski** [comment]
Okay, thanks for the reply!
