### ISSUE TITLE
Constraint Violation as a Penalty - Multi-Objective framework

### ISSUE THREAD

**Issue by AndSalaMove** [anyoptimization/pymoo#465]
Hello,
first of all, thanks for the great package.

I am facing some problems; I would like to implement CV as a penalty:

```
 Id = 1e-6
Vth = 0.7
 Va = 100

    algorithm = NSGA2(
        pop_size=50,
        n_offsprings=20,
        sampling=FloatRandomSampling(),
        crossover=SBX(prob=0.9, eta=15),
        mutation=PM(eta=20),
        eliminate_duplicates=True
    )

    termination = get_termination("n_gen", 100)

    problem = CurrentMirror(
        Id = Id,
        Vth = Vth,
        Va = Va
    )

    res = minimize(
        ConstraintsAsPenalty(problem, penalty=np.array([1,1,100])),
        algorithm,
        termination,
        seed = 42,
        save_history = True,
        verbose = True
    )
```

 but if I include it in my (working) code I get the following error:
```
Traceback (most recent call last):
  File "C:\Users\andreasala\Desktop\projects\circuit-optimizer\optimizer.py", line 121, in <module>
    res = minimize(
  File "C:\Users\andreasala\anaconda3\envs\dev1\lib\site-packages\pymoo\optimize.py", line 67, in minimize
    res = algorithm.run()
  File "C:\Users\andreasala\anaconda3\envs\dev1\lib\site-packages\pymoo\core\algorithm.py", line 141, in run
    self.next()
  File "C:\Users\andreasala\anaconda3\envs\dev1\lib\site-packages\pymoo\core\algorithm.py", line 161, in next
    self.evaluator.eval(self.problem, infills, algorithm=self)
  File "C:\Users\andreasala\anaconda3\envs\dev1\lib\site-packages\pymoo\core\evaluator.py", line 69, in eval
    self._eval(problem, pop[I], evaluate_values_of, **kwargs)
  File "C:\Users\andreasala\anaconda3\envs\dev1\lib\site-packages\pymoo\core\evaluator.py", line 90, in _eval
    out = problem.evaluate(X, return_values_of=evaluate_values_of, return_as_dictionary=True, **kwargs)
  File "C:\Users\andreasala\anaconda3\envs\dev1\lib\site-packages\pymoo\core\problem.py", line 187, in evaluate
    _out = self.do(X, return_values_of, *args, **kwargs)
  File "C:\Users\andreasala\anaconda3\envs\dev1\lib\site-packages\pymoo\constraints\as_penalty.py", line 36, in do
    out["F"] = F + self.penalty * np.reshape(CV, F.shape)
  File "<__array_function__ internals>", line 200, in reshape
  File "C:\Users\andreasala\anaconda3\envs\dev1\lib\site-packages\numpy\core\fromnumeric.py", line 298, in reshape
    return _wrapfunc(a, 'reshape', newshape, order=order)
  File "C:\Users\andreasala\anaconda3\envs\dev1\lib\site-packages\numpy\core\fromnumeric.py", line 57, in _wrapfunc
    return bound(*args, **kwds)
ValueError: cannot reshape array of size 50 into shape (50,3)
```

where 50 is my pop size.

I've already tried to specify an array of penalties instead of a single value, since I have 3 objective functions, but it does not work either.

Is CV as a penalty supported for MOO problems?

Thanks

**Comment by jacktang** [comment]
https://github.com/anyoptimization/pymoo/blob/6fac683d5b9cc8f5c4088e8ad62d01da1cd0a696/pymoo/constraints/as_penalty.py#L35-L36
It seems not support multi-objectives well. You may change the code to `out["F"] = F + self.penalty * np.mean(CV)` to let the code run.

**Comment by AndSalaMove** [comment]
Ok thanks, I'll fork the repo and make my own changes.

**Comment by blankjul** [comment]
If you find a solution that generalizes more can you also create a PR with your fix?

**Comment by AndSalaMove** [comment]
What about a simple

```
try:
    out["F"] = F + self.penalty * np.reshape(CV, F.shape)
except ValueError:
    out["F"] = F + self.penalty * np.sum(CV)
```
?
