### ISSUE TITLE
ValueError: negative dimensions are not allowed

### ISSUE THREAD

**Issue by mhurtado13** [anyoptimization/pymoo#577]
Not sure how to fix it 

```
class calibrationProb(Problem):
    def _init_(self):
        super()._init_(n_var = 10,
                       n_obj = 2,
                       xl = np.array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
                       xu = np.array([2.0, 2.0, 10e-5, 2.0, 50e-2, 2.0, 184e-2, 2.0, 2.0, 8e-2]))
        
    def _evaluate(self, x, out):
        viability, concentration = model_simulation("./config/NLC_CLL.xml", 3, x[0], x[1], x[2], x[3], x[4], x[5], x[6], x[7], x[8], x[9])

        #Objective functions
        obj1 = math.sqrt(((viability - viability_exp)**2)/N) #RMSE of viability
        obj2 = math.sqrt(((concentration - concentration_exp)**2)/N) #RMSE of concentration

        #Stacking objectives to "F" 
        out["F"] = np.column_stack([obj1, obj2])


NLC_problem = calibrationProb()

from pymoo.algorithms.moo.nsga2 import NSGA2
from pymoo.optimize import minimize

algorithm_nsga = NSGA2(pop_size=100)

res = minimize(problem= NLC_problem,
               algorithm=algorithm_nsga,
               seed=1,
               verbose=False)
```

It gives me 

```
(base) marcelo@CRCT2106:~/Documents/REACT/Physicell_NLCs-CLL$ python scripts/function.py
Traceback (most recent call last):
  File "/home/marcelo/Documents/REACT/Physicell_NLCs-CLL/scripts/function.py", line 105, in <module>
    res = minimize(problem= NLC_problem,
  File "/home/marcelo/mambaforge/lib/python3.10/site-packages/pymoo/optimize.py", line 67, in minimize
    res = algorithm.run()
  File "/home/marcelo/mambaforge/lib/python3.10/site-packages/pymoo/core/algorithm.py", line 138, in run
    self.next()
  File "/home/marcelo/mambaforge/lib/python3.10/site-packages/pymoo/core/algorithm.py", line 154, in next
    infills = self.infill()
  File "/home/marcelo/mambaforge/lib/python3.10/site-packages/pymoo/core/algorithm.py", line 186, in infill
    infills = self._initialize_infill()
  File "/home/marcelo/mambaforge/lib/python3.10/site-packages/pymoo/algorithms/base/genetic.py", line 75, in _initialize_infill
    pop = self.initialization.do(self.problem, self.pop_size, algorithm=self)
  File "/home/marcelo/mambaforge/lib/python3.10/site-packages/pymoo/core/initialization.py", line 32, in do
    pop = self.sampling(problem, n_samples, **kwargs)
  File "/home/marcelo/mambaforge/lib/python3.10/site-packages/pymoo/core/operator.py", line 27, in __call__
    out = self.do(problem, elem, *args, **kwargs)
  File "/home/marcelo/mambaforge/lib/python3.10/site-packages/pymoo/core/sampling.py", line 35, in do
    val = self._do(problem, n_samples, **kwargs)
  File "/home/marcelo/mambaforge/lib/python3.10/site-packages/pymoo/operators/sampling/rnd.py", line 20, in _do
    X = np.random.random((n_samples, problem.n_var))
  File "mtrand.pyx", line 445, in numpy.random.mtrand.RandomState.random
  File "mtrand.pyx", line 436, in numpy.random.mtrand.RandomState.random_sample
  File "_common.pyx", line 307, in numpy.random._common.double_fill
ValueError: negative dimensions are not allowed
```

**Comment by mouneem** [comment]
Hello @mhurtado13 
Try using     `def __init__(self) `instead of     `def _init_(self):`
